# Generated by Django 4.2.10 on 2024-05-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='aciklama',
            field=models.TextField(default='açıklama yok'),
            preserve_default=False,
        ),
    ]
